// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TodayImport } from './routes/today'
import { Route as RewardsImport } from './routes/rewards'
import { Route as HistoryImport } from './routes/history'
import { Route as HabitsImport } from './routes/habits'

// Create/Update Routes

const TodayRoute = TodayImport.update({
  path: '/today',
  getParentRoute: () => rootRoute,
} as any)

const RewardsRoute = RewardsImport.update({
  path: '/rewards',
  getParentRoute: () => rootRoute,
} as any)

const HistoryRoute = HistoryImport.update({
  path: '/history',
  getParentRoute: () => rootRoute,
} as any)

const HabitsRoute = HabitsImport.update({
  path: '/habits',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/habits': {
      preLoaderRoute: typeof HabitsImport
      parentRoute: typeof rootRoute
    }
    '/history': {
      preLoaderRoute: typeof HistoryImport
      parentRoute: typeof rootRoute
    }
    '/rewards': {
      preLoaderRoute: typeof RewardsImport
      parentRoute: typeof rootRoute
    }
    '/today': {
      preLoaderRoute: typeof TodayImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  HabitsRoute,
  HistoryRoute,
  RewardsRoute,
  TodayRoute,
])
